version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
    - 1.37.0
  - dependency-name: github.com/go-sql-driver/mysql
    versions:
    - 1.6.0
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
    - 1.5.2
  - dependency-name: github.com/grpc-ecosystem/grpc-gateway
    versions:
    - 1.16.0
  - dependency-name: gopkg.in/yaml.v2
    versions:
    - 2.4.0
