openapi: 3.0.0
info:
    title: grpclab API
    description: grpclab open API documentation
    version: 0.1.0

servers:
  - url: tbd

paths:
  /dev/register:
    post:
      summary: Add a user.
      description: xxx
      responses:
        '200':
          description: Registration success.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string