// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/entitler_api.proto

package gRPCServerClient_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MayIRequest struct {
	UserId               string    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Operation            Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=gRPCServerClient.proto.Operation" json:"operation,omitempty"`
	AccountId            string    `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MayIRequest) Reset()         { *m = MayIRequest{} }
func (m *MayIRequest) String() string { return proto.CompactTextString(m) }
func (*MayIRequest) ProtoMessage()    {}
func (*MayIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83eeea8cd3c9792, []int{0}
}

func (m *MayIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MayIRequest.Unmarshal(m, b)
}
func (m *MayIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MayIRequest.Marshal(b, m, deterministic)
}
func (m *MayIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MayIRequest.Merge(m, src)
}
func (m *MayIRequest) XXX_Size() int {
	return xxx_messageInfo_MayIRequest.Size(m)
}
func (m *MayIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MayIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MayIRequest proto.InternalMessageInfo

func (m *MayIRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MayIRequest) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_OPERATION_INVALID
}

func (m *MayIRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type MayIResponse struct {
	YouMay               bool     `protobuf:"varint,1,opt,name=you_may,json=youMay,proto3" json:"you_may,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MayIResponse) Reset()         { *m = MayIResponse{} }
func (m *MayIResponse) String() string { return proto.CompactTextString(m) }
func (*MayIResponse) ProtoMessage()    {}
func (*MayIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83eeea8cd3c9792, []int{1}
}

func (m *MayIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MayIResponse.Unmarshal(m, b)
}
func (m *MayIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MayIResponse.Marshal(b, m, deterministic)
}
func (m *MayIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MayIResponse.Merge(m, src)
}
func (m *MayIResponse) XXX_Size() int {
	return xxx_messageInfo_MayIResponse.Size(m)
}
func (m *MayIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MayIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MayIResponse proto.InternalMessageInfo

func (m *MayIResponse) GetYouMay() bool {
	if m != nil {
		return m.YouMay
	}
	return false
}

func (m *MayIResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ListMeRequest struct {
	UserId               string    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Operation            Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=gRPCServerClient.proto.Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMeRequest) Reset()         { *m = ListMeRequest{} }
func (m *ListMeRequest) String() string { return proto.CompactTextString(m) }
func (*ListMeRequest) ProtoMessage()    {}
func (*ListMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83eeea8cd3c9792, []int{2}
}

func (m *ListMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeRequest.Unmarshal(m, b)
}
func (m *ListMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeRequest.Marshal(b, m, deterministic)
}
func (m *ListMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeRequest.Merge(m, src)
}
func (m *ListMeRequest) XXX_Size() int {
	return xxx_messageInfo_ListMeRequest.Size(m)
}
func (m *ListMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeRequest proto.InternalMessageInfo

func (m *ListMeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListMeRequest) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_OPERATION_INVALID
}

type ListMeResponse struct {
	Permission           []*AccountPermissions `protobuf:"bytes,1,rep,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListMeResponse) Reset()         { *m = ListMeResponse{} }
func (m *ListMeResponse) String() string { return proto.CompactTextString(m) }
func (*ListMeResponse) ProtoMessage()    {}
func (*ListMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83eeea8cd3c9792, []int{3}
}

func (m *ListMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeResponse.Unmarshal(m, b)
}
func (m *ListMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeResponse.Marshal(b, m, deterministic)
}
func (m *ListMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeResponse.Merge(m, src)
}
func (m *ListMeResponse) XXX_Size() int {
	return xxx_messageInfo_ListMeResponse.Size(m)
}
func (m *ListMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeResponse proto.InternalMessageInfo

func (m *ListMeResponse) GetPermission() []*AccountPermissions {
	if m != nil {
		return m.Permission
	}
	return nil
}

type AccountPermissions struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Operations           []Operation `protobuf:"varint,2,rep,packed,name=operations,proto3,enum=gRPCServerClient.proto.Operation" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountPermissions) Reset()         { *m = AccountPermissions{} }
func (m *AccountPermissions) String() string { return proto.CompactTextString(m) }
func (*AccountPermissions) ProtoMessage()    {}
func (*AccountPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83eeea8cd3c9792, []int{4}
}

func (m *AccountPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPermissions.Unmarshal(m, b)
}
func (m *AccountPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPermissions.Marshal(b, m, deterministic)
}
func (m *AccountPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPermissions.Merge(m, src)
}
func (m *AccountPermissions) XXX_Size() int {
	return xxx_messageInfo_AccountPermissions.Size(m)
}
func (m *AccountPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPermissions proto.InternalMessageInfo

func (m *AccountPermissions) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountPermissions) GetOperations() []Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*MayIRequest)(nil), "gRPCServerClient.proto.MayIRequest")
	proto.RegisterType((*MayIResponse)(nil), "gRPCServerClient.proto.MayIResponse")
	proto.RegisterType((*ListMeRequest)(nil), "gRPCServerClient.proto.ListMeRequest")
	proto.RegisterType((*ListMeResponse)(nil), "gRPCServerClient.proto.ListMeResponse")
	proto.RegisterType((*AccountPermissions)(nil), "gRPCServerClient.proto.AccountPermissions")
}

func init() { proto.RegisterFile("proto/entitler_api.proto", fileDescriptor_d83eeea8cd3c9792) }

var fileDescriptor_d83eeea8cd3c9792 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xdd, 0x4a, 0xc3, 0x30,
	0x18, 0x35, 0x9b, 0x54, 0xfb, 0x4d, 0x77, 0x91, 0x8b, 0x59, 0x0a, 0x42, 0xad, 0x3f, 0x0c, 0x2f,
	0x26, 0xcc, 0x07, 0x18, 0x63, 0x78, 0x51, 0x71, 0x38, 0xb2, 0x2b, 0x41, 0x18, 0x71, 0xfb, 0x90,
	0xc0, 0xd6, 0xd4, 0x24, 0x1d, 0xf4, 0x05, 0x7c, 0x2b, 0xdf, 0x4d, 0xda, 0x74, 0x73, 0x4e, 0xab,
	0xde, 0x78, 0x99, 0x93, 0x73, 0x4e, 0xce, 0x77, 0xf2, 0x81, 0x97, 0x28, 0x69, 0xe4, 0x15, 0xc6,
	0x46, 0x98, 0x39, 0xaa, 0x09, 0x4f, 0x44, 0xa7, 0x80, 0x68, 0xeb, 0x99, 0x8d, 0x06, 0x63, 0x54,
	0x4b, 0x54, 0x83, 0xb9, 0xc0, 0xd8, 0x58, 0xdc, 0xf7, 0xb7, 0x14, 0x26, 0x4b, 0x50, 0xdb, 0xbb,
	0xf0, 0x95, 0x40, 0x63, 0xc8, 0xb3, 0x88, 0xe1, 0x4b, 0x8a, 0xda, 0xd0, 0x23, 0xd8, 0x4b, 0x35,
	0xaa, 0x89, 0x98, 0x79, 0x24, 0x20, 0x6d, 0x97, 0x39, 0xf9, 0x31, 0x9a, 0xd1, 0x1e, 0xb8, 0x32,
	0x41, 0xc5, 0x8d, 0x90, 0xb1, 0x57, 0x0b, 0x48, 0xbb, 0xd9, 0x3d, 0xe9, 0x7c, 0xff, 0x60, 0xe7,
	0x7e, 0x45, 0x64, 0x1f, 0x1a, 0x7a, 0x0c, 0xc0, 0xa7, 0x53, 0x99, 0xc6, 0x26, 0x37, 0xaf, 0x17,
	0xe6, 0x6e, 0x89, 0x44, 0xb3, 0xb0, 0x07, 0x07, 0x36, 0x87, 0x4e, 0x64, 0xac, 0x31, 0x0f, 0x92,
	0xc9, 0x74, 0xb2, 0xe0, 0x59, 0x11, 0x64, 0x9f, 0x39, 0x99, 0x4c, 0x87, 0x3c, 0xa3, 0x2d, 0x70,
	0x14, 0x72, 0x5d, 0xa6, 0x70, 0x59, 0x79, 0x0a, 0x05, 0x1c, 0xde, 0x09, 0x6d, 0x86, 0xf8, 0xef,
	0xa3, 0x84, 0x8f, 0xd0, 0x5c, 0x3d, 0x55, 0xa6, 0xbd, 0x05, 0x48, 0x50, 0x2d, 0x84, 0xd6, 0xb9,
	0x27, 0x09, 0xea, 0xed, 0x46, 0xf7, 0xb2, 0xca, 0xb3, 0x6f, 0x87, 0x1e, 0xad, 0x05, 0x9a, 0x6d,
	0xa8, 0xc3, 0x25, 0xd0, 0xaf, 0x8c, 0xad, 0xfa, 0xc8, 0x56, 0x7d, 0xb4, 0x0f, 0xb0, 0xce, 0xa7,
	0xbd, 0x5a, 0x50, 0xff, 0xdb, 0x50, 0x1b, 0xa2, 0xee, 0x1b, 0x81, 0xc6, 0x4d, 0xb9, 0x23, 0xfd,
	0x51, 0x44, 0xc7, 0xb0, 0x9b, 0xff, 0x08, 0x3d, 0xad, 0xb2, 0xd9, 0xd8, 0x1b, 0xff, 0xec, 0x67,
	0x92, 0xad, 0x29, 0xdc, 0xa1, 0x0f, 0xe0, 0xd8, 0xea, 0xe8, 0x79, 0x95, 0xe2, 0xd3, 0x2f, 0xfa,
	0x17, 0xbf, 0xd1, 0x56, 0xd6, 0x4f, 0x4e, 0x81, 0x5f, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0xdd,
	0xde, 0x09, 0x24, 0x21, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntitlerAPIClient is the client API for EntitlerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntitlerAPIClient interface {
	MayI(ctx context.Context, in *MayIRequest, opts ...grpc.CallOption) (*MayIResponse, error)
	ListMe(ctx context.Context, in *ListMeRequest, opts ...grpc.CallOption) (*ListMeResponse, error)
}

type entitlerAPIClient struct {
	cc *grpc.ClientConn
}

func NewEntitlerAPIClient(cc *grpc.ClientConn) EntitlerAPIClient {
	return &entitlerAPIClient{cc}
}

func (c *entitlerAPIClient) MayI(ctx context.Context, in *MayIRequest, opts ...grpc.CallOption) (*MayIResponse, error) {
	out := new(MayIResponse)
	err := c.cc.Invoke(ctx, "/gRPCServerClient.proto.EntitlerAPI/MayI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlerAPIClient) ListMe(ctx context.Context, in *ListMeRequest, opts ...grpc.CallOption) (*ListMeResponse, error) {
	out := new(ListMeResponse)
	err := c.cc.Invoke(ctx, "/gRPCServerClient.proto.EntitlerAPI/ListMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitlerAPIServer is the server API for EntitlerAPI service.
type EntitlerAPIServer interface {
	MayI(context.Context, *MayIRequest) (*MayIResponse, error)
	ListMe(context.Context, *ListMeRequest) (*ListMeResponse, error)
}

// UnimplementedEntitlerAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEntitlerAPIServer struct {
}

func (*UnimplementedEntitlerAPIServer) MayI(ctx context.Context, req *MayIRequest) (*MayIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MayI not implemented")
}
func (*UnimplementedEntitlerAPIServer) ListMe(ctx context.Context, req *ListMeRequest) (*ListMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMe not implemented")
}

func RegisterEntitlerAPIServer(s *grpc.Server, srv EntitlerAPIServer) {
	s.RegisterService(&_EntitlerAPI_serviceDesc, srv)
}

func _EntitlerAPI_MayI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MayIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlerAPIServer).MayI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPCServerClient.proto.EntitlerAPI/MayI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlerAPIServer).MayI(ctx, req.(*MayIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlerAPI_ListMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlerAPIServer).ListMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPCServerClient.proto.EntitlerAPI/ListMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlerAPIServer).ListMe(ctx, req.(*ListMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntitlerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gRPCServerClient.proto.EntitlerAPI",
	HandlerType: (*EntitlerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MayI",
			Handler:    _EntitlerAPI_MayI_Handler,
		},
		{
			MethodName: "ListMe",
			Handler:    _EntitlerAPI_ListMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/entitler_api.proto",
}
