// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goate_api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88176d77a4152c76, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type LoginResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88176d77a4152c76, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88176d77a4152c76, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type ChangePasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88176d77a4152c76, []int{3}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88176d77a4152c76, []int{4}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "goate.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "goate.LoginResponse")
	proto.RegisterType((*RegisterResponse)(nil), "goate.RegisterResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "goate.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "goate.ChangePasswordResponse")
}

func init() {
	proto.RegisterFile("goate_api.proto", fileDescriptor_88176d77a4152c76)
}

var fileDescriptor_88176d77a4152c76 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x8a, 0xfa, 0x72, 0x4b, 0x1f, 0xa6, 0x85, 0x28, 0x14, 0x09, 0x7c, 0x82, 0x1e, 0x1a,
	0x09, 0x6e, 0xbd, 0x41, 0x85, 0x10, 0x12, 0x48, 0x55, 0xb8, 0x71, 0xa9, 0x4c, 0xb2, 0x0a, 0x46,
	0xc1, 0x0e, 0xb6, 0x4b, 0xd5, 0x2b, 0xbf, 0xd0, 0x4f, 0xe3, 0x17, 0xf8, 0x10, 0x14, 0xc7, 0x29,
	0x94, 0xc7, 0xc9, 0xda, 0xd9, 0xd9, 0xd9, 0x9d, 0x91, 0x51, 0x3b, 0x16, 0x54, 0xc3, 0x8c, 0xa6,
	0x6c, 0x94, 0x4a, 0xa1, 0x05, 0x2e, 0x1b, 0xc0, 0x1b, 0xc4, 0x42, 0xc4, 0x09, 0xf8, 0x34, 0x65,
	0x3e, 0xe5, 0x5c, 0x68, 0xaa, 0x99, 0xe0, 0x2a, 0x27, 0x79, 0xdd, 0x7c, 0x4a, 0x2f, 0x53, 0xb0,
	0x10, 0x69, 0xa1, 0xe6, 0x8d, 0x88, 0x19, 0x0f, 0xe0, 0x65, 0x0e, 0x4a, 0x93, 0x13, 0xb4, 0x6d,
	0x6b, 0x95, 0x0a, 0xae, 0x00, 0xbb, 0xa8, 0xaa, 0xe6, 0x61, 0x08, 0x4a, 0xb9, 0xce, 0xa1, 0x73,
	0x5c, 0x0b, 0x8a, 0x92, 0x60, 0xd4, 0x09, 0x20, 0x66, 0x4a, 0x83, 0x2c, 0xd8, 0x64, 0x89, 0xfa,
	0x93, 0x47, 0xca, 0x63, 0x98, 0x52, 0xa5, 0x16, 0x42, 0x46, 0x56, 0x17, 0x7b, 0xa8, 0x36, 0x57,
	0x20, 0x39, 0x7d, 0x06, 0xa3, 0x53, 0x0f, 0xd6, 0x35, 0x3e, 0x42, 0x4d, 0x91, 0x44, 0xb3, 0xd4,
	0x8e, 0xb8, 0x25, 0xd3, 0x6f, 0x88, 0x24, 0x2a, 0x54, 0x32, 0x0a, 0x87, 0xc5, 0x17, 0x65, 0x2b,
	0xa7, 0x70, 0x58, 0x14, 0x14, 0xe2, 0xa2, 0xdd, 0x9f, 0xab, 0xf3, 0xa3, 0x4e, 0x57, 0x25, 0xd4,
	0xbe, 0xca, 0x9c, 0x9f, 0x4f, 0xaf, 0xef, 0x40, 0xbe, 0xb2, 0x10, 0xf0, 0x2d, 0xaa, 0x15, 0xc7,
	0x63, 0x3c, 0x32, 0xb9, 0x8c, 0x26, 0x12, 0x22, 0xe0, 0x9a, 0xd1, 0x44, 0x79, 0x7b, 0x16, 0xfb,
	0xe5, 0xb0, 0xf7, 0xf6, 0xfe, 0xb1, 0x2a, 0xb5, 0x48, 0xdd, 0x97, 0xb6, 0x35, 0x76, 0x86, 0xf8,
	0x12, 0x95, 0x4d, 0x6c, 0x78, 0xc7, 0xce, 0x7d, 0x0f, 0xd5, 0xeb, 0x6d, 0x82, 0x56, 0xa9, 0x6b,
	0x94, 0x1a, 0xa4, 0xe2, 0x27, 0x19, 0x9e, 0xc9, 0x3c, 0xa1, 0xd6, 0xa6, 0x07, 0x3c, 0x28, 0x6e,
	0xfb, 0x2b, 0x55, 0xef, 0xe0, 0x9f, 0xae, 0xdd, 0xb0, 0x6f, 0x36, 0xf4, 0x49, 0xc7, 0x0f, 0x0d,
	0x61, 0x9d, 0xdf, 0xd8, 0x19, 0x5e, 0x54, 0xef, 0xcb, 0xe6, 0x0b, 0x3c, 0x54, 0xcc, 0x73, 0xf6,
	0x19, 0x00, 0x00, 0xff, 0xff, 0xce, 0x77, 0x3f, 0xd4, 0x54, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoateAPIServiceClient is the client API for GoateAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoateAPIServiceClient interface {
	Register(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
}

type goateAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoateAPIServiceClient(cc grpc.ClientConnInterface) GoateAPIServiceClient {
	return &goateAPIServiceClient{cc}
}

func (c *goateAPIServiceClient) Register(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/goate.GoateAPIService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goateAPIServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/goate.GoateAPIService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goateAPIServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/goate.GoateAPIService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoateAPIServiceServer is the server API for GoateAPIService service.
type GoateAPIServiceServer interface {
	Register(context.Context, *Credentials) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
}

// UnimplementedGoateAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGoateAPIServiceServer struct {
}

func (*UnimplementedGoateAPIServiceServer) Register(ctx context.Context, req *Credentials) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedGoateAPIServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedGoateAPIServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}

func RegisterGoateAPIServiceServer(s *grpc.Server, srv GoateAPIServiceServer) {
	s.RegisterService(&_GoateAPIService_serviceDesc, srv)
}

func _GoateAPIService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoateAPIServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goate.GoateAPIService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoateAPIServiceServer).Register(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoateAPIService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoateAPIServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goate.GoateAPIService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoateAPIServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoateAPIService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoateAPIServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goate.GoateAPIService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoateAPIServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoateAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goate.GoateAPIService",
	HandlerType: (*GoateAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GoateAPIService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GoateAPIService_Login_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _GoateAPIService_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goate_api.proto",
}
