name: Docker Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: lint
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
