name: Code quality check
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'deployments/**'
    - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-contrib/golangci-lint@v1